"""contribution

Revision ID: 7cb4d4b01470
Revises: 66d1517e517f
Create Date: 2025-07-17 15:19:04.684181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7cb4d4b01470'
down_revision: Union[str, None] = '66d1517e517f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('published_by',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('data_embargo',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('study_identifier',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_contribution_id'),
                    'contribution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_id'), table_name='contribution')
    op.drop_table('contribution')
    # ### end Alembic commands ###
