"""certification

Revision ID: af3241850881
Revises: 54689698d524
Create Date: 2025-05-28 08:11:34.091679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3241850881'
down_revision: Union[str, None] = '54689698d524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certification', 'program',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certification', 'program',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
