"""new_fields

Revision ID: 54689698d524
Revises: 1edb7ed84236
Create Date: 2025-05-19 15:51:49.388356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54689698d524'
down_revision: Union[str, None] = '1edb7ed84236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('renovation_details',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('space', sa.Column(
        'occupancy_number', sa.Integer(), nullable=True))
    op.add_column('study', sa.Column('data_processing',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'data_processing')
    op.drop_column('space', 'occupancy_number')
    op.drop_column('building', 'renovation_details')
    # ### end Alembic commands ###
