"""json

Revision ID: 66d1517e517f
Revises: af3241850881
Create Date: 2025-05-30 08:53:57.381129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66d1517e517f'
down_revision: Union[str, None] = 'af3241850881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'folder',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'folder',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###
