"""measurements

Revision ID: ac49ec1ab264
Revises: 7cb4d4b01470
Create Date: 2026-09-22 16:07:17.110271

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac49ec1ab264"
down_revision: Union[str, None] = "7cb4d4b01470"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AGGREGATE_KEYS = "dataset_id, study_id, building_id, space_id, instrument_id, parameter"


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parameter",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "conversions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "benchmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("averaging", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["parameter"], ["parameter.slug"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_parameter",
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("parameter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("n_records", sa.BigInteger(), nullable=False),
        sa.Column("n_missing", sa.BigInteger(), nullable=False),
        sa.Column("first_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("last_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("n_buildings", sa.Integer(), nullable=False),
        sa.Column("n_spaces", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parameter"], ["parameter.slug"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dataset_id", "parameter"),
    )
    op.create_table(
        "measurement",
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("space_id", sa.Integer(), nullable=True),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("parameter", sa.String(), nullable=False),
        sa.Column("data_type", sa.String(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(), nullable=False),
        sa.Column("start_ts", sa.TIMESTAMP(), nullable=True),
        sa.Column("end_ts", sa.TIMESTAMP(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("value_qualifier", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["building_id"], ["building.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instrument.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["parameter"], ["parameter.slug"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["space.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["study_id"], ["study.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_measurement_dataset_parameter_ts",
        "measurement",
        ["dataset_id", "parameter", "ts"],
        unique=False,
    )
    op.create_index(
        "ix_measurement_parameter_ts", "measurement", ["parameter", "ts"], unique=False
    )
    op.create_index(
        "ix_measurement_space_ts", "measurement", ["space_id", "ts"], unique=False
    )
    op.add_column(
        "dataset",
        sa.Column(
            "summary_status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column(
        "dataset",
        sa.Column("summary_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "dataset",
        sa.Column(
            "load_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###

    # TimescaleDB: hypertable, compression and the continuous aggregates.
    # Not expressible in model code (see docs/129-explore-charts-api.md §3).
    op.execute("INSERT INTO catalog_version (id, version) VALUES (1, 1)")
    op.execute(
        "SELECT create_hypertable('measurement', 'ts',"
        " chunk_time_interval => INTERVAL '1 month')"
    )
    op.execute(
        "ALTER TABLE measurement SET (timescaledb.compress,"
        " timescaledb.compress_segmentby = 'dataset_id, space_id, parameter',"
        " timescaledb.compress_orderby = 'ts DESC')"
    )
    # WITH NO DATA keeps the creation transactional; loads refresh explicitly
    op.execute(
        f"""
        CREATE MATERIALIZED VIEW measurement_hour
        WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
        SELECT {AGGREGATE_KEYS},
               time_bucket(INTERVAL '1 hour', ts) AS hour,
               count(*) AS n, avg(value) AS mean,
               min(value) AS min, max(value) AS max
        FROM measurement
        WHERE data_type <> 'statistical'
        GROUP BY {AGGREGATE_KEYS}, hour
        WITH NO DATA
        """
    )
    op.execute(
        f"""
        CREATE MATERIALIZED VIEW measurement_day
        WITH (timescaledb.continuous, timescaledb.materialized_only = true) AS
        SELECT {AGGREGATE_KEYS},
               time_bucket(INTERVAL '1 day', hour) AS day,
               sum(n) AS n, sum(mean * n) / sum(n) AS mean,
               min(min) AS min, max(max) AS max
        FROM measurement_hour
        GROUP BY {AGGREGATE_KEYS}, day
        WITH NO DATA
        """
    )
    # the (key, bucket) indexes come with the aggregates (create_group_indexes)
    for view, bucket in (("measurement_hour", "hour"), ("measurement_day", "day")):
        op.execute(
            f"CREATE INDEX ix_{view}_dataset_parameter_{bucket}"
            f" ON {view} (dataset_id, parameter, {bucket})"
        )


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW measurement_day")
    op.execute("DROP MATERIALIZED VIEW measurement_hour")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "load_report")
    op.drop_column("dataset", "summary_error")
    op.drop_column("dataset", "summary_status")
    op.drop_index("ix_measurement_space_ts", table_name="measurement")
    op.drop_index("ix_measurement_parameter_ts", table_name="measurement")
    op.drop_index("ix_measurement_dataset_parameter_ts", table_name="measurement")
    op.drop_table("measurement")
    op.drop_table("dataset_parameter")
    op.drop_table("benchmark")
    op.drop_table("parameter")
    op.drop_table("catalog_version")
    # ### end Alembic commands ###
